### ISSUE TITLE
Write normalize case macro

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#105]
We are using translation maps to normalize language codes (e.g. iso 639-1) and non-English language values (e.g. Turkish words for languages). We also need a macro to normalize case to resolve issues where (e.g. 'persian' and 'Persian' end up in the DLME application).

Acceptance criteria:
- [ ] pass any variation of capital and lowercase letters and return the first letter of each word capitalized (e.g. 'turkish, ottoman', 'Turkish, Ottoman', 'TURKISH, OTTOMAN, Turkish, ottoman' -> 'Turkish, Ottoman')

**Comment by justinlittman** [comment]
Similar to how you use `transform(&:downcase)`, you can use `transform(&:titleize)`. This may require `require 'active_support/core_ext/string/inflections'`.

See the example below:
```
# frozen_string_literal: true
require 'active_support/core_ext/string/inflections'


RSpec.describe 'titleize' do
  let(:transform) do
    indexer = Traject::Indexer.new
    this = self
    indexer.configure do
      to_field 'test_field', literal(this.value), transform(&:titleize)
    end
    indexer.map_record(nil)['test_field']
  end

  context 'for an all caps value' do
    let(:value) { 'FOO BAR' }
    it 'correctly capitalizes' do
      expect(transform).to eq(['Foo Bar'])
    end
  end

  context 'for an all lower value' do
    let(:value) { 'foo bar' }
    it 'correctly capitalizes' do
      expect(transform).to eq(['Foo Bar'])
    end
  end

  context 'for a mixed cap value' do
    let(:value) { 'foo Bar' }
    it 'correctly capitalizes' do
      expect(transform).to eq(['Foo Bar'])
    end
  end

end
```

Does that work?

**Comment by jacobthill** [comment]
I think it is causing conflicts with `Not Found`. I'm now getting `NOT FOUND` errors for values like "English" and "French". I need to run `&titleize` and `not_found` on the same data set because there are mixed values for the language fields. e.g. things like "French", "french", and "fr" are all in the same data set. I'm not sure how to resolve this. Here is an updated pass at acceptance criteria:
- [ ] raw language values other than English words for the language (e.g. "fr", "ara", "ermenice") need to to be passed to translation map and I need a `NOT FOUND` error if those values are not in the translation map
- [ ] English language words for the languages (e.g. "french", "Arabic", "PERSIAN") need to be `&titleized` 
- [ ] `&titleize` and `not_found` need to work on the same dataset without conflict

**Comment by justinlittman** [comment]
Can you provide an example of where it is not working? That is, both the config and input.

**Comment by jacobthill** [comment]
Actually disregard that. I was running `&titleize` before `not_found` which caused errors but switching the order works.

**Comment by jacobthill** [comment]
Spoke too soon. I'll push up the code.

**Comment by jacobthill** [comment]
Here is the branch: https://github.com/sul-dlss/dlme-traject/tree/auc-config. You can run it on the whole auc directory and get several examples.

**Comment by justinlittman** [comment]
Give this branch of dlme-transform a try: https://github.com/sul-dlss/dlme-transform/tree/not_found

**Comment by jacobthill** [comment]
I'm getting the same errors on that branch

**Comment by justinlittman** [comment]
What errors are you getting? Can you provide the exact commandline you're running?

**Comment by jacobthill** [comment]
`docker run --rm -e SKIP_FETCH_CONFIG=true                 -e SKIP_FETCH_DATA=true                 -v $(pwd)/.:/opt/traject                 -v $(pwd)/../dlme-traject:/opt/traject/config                 -v $(pwd)/../dlme-metadata:/opt/traject/data                 -v $(pwd)/output:/opt/traject/output                 suldlss/dlme-transform:latest                 auc`

dlme-transform is on `not_found` branch
dlme-traject is on `auc-config` branch

**Comment by jacobthill** [comment]
There are a lot of `NOT_FOUND` errors for language

**Comment by justinlittman** [comment]
Can you give an example of an error that is Not Found that you expect to be found? Sorry to be dense, but I'm really not familiar with the data and expected transformations. It really helps to have a specific, reproducible example.

**Comment by jacobthill** [comment]
`The errors are: {"cho_language"=>{0=>["must not be one of: Not Found"]}}

The data looked like this:
{
  "cho_title": [
    "Sesostris Street"
  ],
  "cho_coverage": [
    "Alexandria; Al-Iskandarīyah governorate; Egypt; Africa"
  ],
  "cho_creator": [
    "Fiorillo, L ",
    ", 1870-1889"
  ],
  "cho_date": [
    "1882"
  ],
  "cho_description": [
    "Photographer's description: La rue Sésostris (ruines). Translation of photographer's description: Sesostris street (ruins)."
  ],
  "cho_dc_rights": [
    "This item is in the public domain.",
    "To inquire about permissions or reproductions, contact the Rare Books and Special Collections Library, The American University in Cairo at +20.2.2615.3676 or rbscl-ref@aucegypt.edu."
  ],
  "cho_edm_type": [
    "image"
  ],
  "cho_format": [
    "image/jp2",
    "26.7 x 18.9 cm.",
    "albumen prints"
  ],
  "cho_language": [
    "Not Found",
    "French"
  ],
  "cho_relation": [
    "Alexandria Bombardment of 1882 Photographs"
  ],
  "cho_subject": [
    "Alexandria (Egypt)--History--Bombardment, 1882.",
    "Buildings; Streets; War damage"
  ],
  "id": "SC-1956-01-PA-1882-01-041_39",
  "agg_data_provider": "American University in Cairo",
  "agg_provider": "American University in Cairo"
}`
I don't expect it to be found though since "French" is not in the translation map. To be clear both `not_found` and `&titleize` seem to be working. There just not working together. I have to use one or the other and I need to use both together.

**Comment by justinlittman** [comment]
Still confused. So this example is working correctly or not working?

**Comment by jacobthill** [comment]
Ok let me try to explain the process from a different angle. I have data sets with all kinds of values in the language field–"ara", "French", "en" "spanish", etc.. I need the values to come through like "Arabic", "French", "English", "Spanish." That is happening, so in that sense its working and the output is what I want. But I'm still getting a NOT FOUND error message because the values "French", etc. are not in the translation map. Here is the line of code I use:

`to_field 'cho_language', extract_oai('dc:language'), split(';'),
         split(','), strip, translation_map('not_found', 'languages', 'marc_languages'), transform(&:titleize)`

So it splits for multiple language values, strips white space, and passes the values (e.g. "ara", "French", "en" "spanish") to the translation map. "ara" and "en" are found so no error occurs, but Spanish is `&titleized` and "Spanish" and "French" result in an NOT FOUND error. I'm not sure what the solution is. One solution would be to add "Spanish", "French" and every other language term to the translation map and then `not_found` would only complain if values like "en" or misspellings, etc. were not in the translation map. I can do that if necessary but , in that case, I can just ignore `&titleize` and use the built in `&downcase` and then map the down case values back to title case in the translation map. I will do that if you can't think of a solution for this. What I was hoping for was a way to raise an error for language values in abnormal form (e.g. "en") but not complain for values in normal form (e.g. "English"). This might be too complex. If you can't think of a way to do this I can just `&downcase` everything and map it to tile case in the translation map.
