### ISSUE TITLE
Refactor stanford config

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#147]
The Stanford items don’t have urls (agg_is_shown_at) or thumbnails (agg_has_preview), probably because when we refactored the repos we stopped using the `stanford_mods_config.rb`.

The Stanford config was not refactored when the github repos were split. Consequently, there is a `stanford_mods_config.rb` in `dlme-traject` that is not used by anything and the `mods_config.rb` that is currently used to transform Stanford values is not returning `agg_is_shown_at`, `agg_has_preview`, and possibly other values. Requirements:
- [x] refactor `stanford_mods_config.rb` (seems to involve mainly refactoring the requirements and extensions)
- [x] possibly add both `mods_config.rb` and `stanford_mods_config.rb` to `metadata_mappigs.json` or maybe all we need is `stanford_mods_config.rb`
- [x] confirm that `agg_is_shown_at` and `agg_has_preview` are being returned correctly
- [x] check to ensure other values that should be returned are being returned
- [x] ensure that cho_edm_type still returns only 'Image'

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss/dlme-traject/blob/master/stanford_mods_config.rb#L3

**Comment by jacobthill** [comment]
@anarchivist there are three missing thumbnails. I think its ok to close this but I'll leave that to you. I plan to revisit this once I have more experience extracting thumbnails so hopefully I can find a solution in the future

**Comment by anarchivist** [comment]
@jacobthill OK, sounds good. It looks like there are other but related issues with the three records that don't have thumbnails - they're missing druids within the records themselves, meaning that the links won't work. I'll create an issue for them but we probably need another way to address the issue.
