### ISSUE TITLE
Princeton records transformed doesn't match records added

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#158]
I transformed princeton records in stage which resulted in 1580 records. After a few days the number of records in stage is now 524 though no changes have been made. Records seem to be leaking out of the database. I'm not sure if these are two different issues or one issue with two different symptoms. 

Steps to reproduce error:
1. delete records from stage 
-https://spotlight.stage.dlmenetwork.org/
-sign in and select 'exhibit dashboard' from the dropdown menu in the top right corner
-select 'items' on the left
-select 'delete items' in the middle of the page
-paste https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-75157840-4961-451e-874a-7d5dc69d30cc.ndjson
-make sure records are deleted (if this does not work, wait until https://github.com/sul-dlss/dlme/issues/527 is resolved and try again)
2. add records again
-https://spotlight.stage.dlmenetwork.org/
-select 'transform data' from the dropdown menu in the top right corner
-select 'transform data' tab
-type 'princeton/islamic-manuscripts' 
-select 'begin transform'
-select 'transform results' tab and refresh until the new aws path appears
-copy aws path
-navigate to home page
-select 'exhibit dashboard' from the dropdown menu in the top right corner
-select 'items' on the left
-select 'add items' in the middle of the page
-select 'DLME S3 Fetch' tab
-paste aws path
-select 'Fetch'
-navigate to home page and select the 'Source Institution' facet
-select 'Princeton University Library'
-refresh until records are finished processing
-check the number of records added

**Comment by jacobthill** [comment]
A similar problem occurred loading bodleian and harvard data in dev; fewer records were loaded than were transformed.

**Comment by mjgiarlo** [comment]
Chatted with @jacobthill yesterday and we determined that the undercounts are due to the fetch JSON containing records w/ duplicate identifiers. We will validate that the S3 Fetch URL content only contains unique records at point of upload for now. See https://github.com/sul-dlss/dlme/pull/582
