### ISSUE TITLE
Use traject 3 pipeline in tei macro

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#161]
https://github.com/sul-dlss/dlme-transform/blob/master/lib/macros/tei.rb and https://github.com/sul-dlss/dlme-traject/blob/master/openn_config.rb result in deprecation warnings. The macro needs to be refactored and the config should be adjusted accordingly:
- [ ] Fix deprecation warnings
- [ ] Remove unused methods from tei.rb

**Comment by ndushay** [comment]
Errors when xforming penn data:

```
[ERROR] Error loading configuration file config/tei_config.rb:46 ArgumentError:wrong number of arguments (given 2, expected 1)
/usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer.rb:231:in `rescue in block in load_config_file': Error loading configuration file config/tei_config.rb:46 ArgumentError:wrong number of arguments (given 2, expected 1) (Traject::Indexer::ConfigLoadError)
```

**Comment by ndushay** [comment]
Running stanford:

```
2019-09-26T22:24:01+00:00  INFO    Traject::Indexer with 1 processing threads, reader: TrajectPlus::XmlReader and writer: DlmeJsonResourceWriter
DEPRECATION WARNING: passing options to extract_xml is deprecated and will be removed in the next major release. Use the Traject 3 pipeline instead. (called from block (2 levels) in first at /usr/local/bundle/gems/traject_plus-1.3.0/lib/traject_plus/macros.rb:28)
DEPRECATION WARNING: passing options to extract_xml is deprecated and will be removed in the next major release. Use the Traject 3 pipeline instead. (called from block in execute at /usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer/step.rb:140)
```

**Comment by jcoyne** [comment]
@jacobthill It doesn't look like https://github.com/sul-dlss/dlme-traject/blob/master/tei_config.rb exists anymore.  Does this ticket need to be revised?

**Comment by jacobthill** [comment]
@jcoyne renamed to openn_config.rb so I didn't attempt to use it on other tei data.

**Comment by jcoyne** [comment]
I'm not sure we can do anything on this other than update to traject_plus 2 since all these originate within traject_plus 1.3

**Comment by aaron-collier** [comment]
Closing. I think this is limited by traject_plus 2, and we can revisit then.
