### ISSUE TITLE
Update text content

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#166]
- [ ] update text on landing page
- [ ] update text on about page
- [ ] add contributors page

**Comment by ewaraksa** [comment]
Updated text drafts in this doc
https://docs.google.com/document/d/1BglICcvC6lVDpEuPx8v2VAKjG3Rz7yi3A0JGCwKxMf4/edit#

**Comment by jcoyne** [comment]
@jacobthill this should probably move to the interface repository: https://github.com/sul-dlss/dlme
