### ISSUE TITLE
Modify type translation maps to support Arabic and English

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#171]
Requirements:
- [ ] The current cho_edm_type values come from the following translation maps: 'types.yaml', 'marc-types.yaml', 'turkish-types.yaml' and 'french-types.yaml'. Since we will be adding values for cho_has_type, these translation maps should be renamed to 'edm-types.yaml', 'edm-marc-types.yaml', 'edm-turkish-types.yaml' and 'edm-french-types.yaml'
- [ ] All of the translation maps need an Arabic equivalent (e.g. 'edm-types-ar.yaml', 'edm-marc-types-ar.yaml', 'edm-turkish-types-ar.yaml' and 'edm-french-types-ar.yaml') with Arabic values

**Comment by cbeer** [comment]
I suspect traject would be happier if we just supplied had different translation maps for each language (and a pattern found... most other places... in Rails-land too).

**Comment by jacobthill** [comment]
@cbeer that makes sense. I've updated the requirements.
