### ISSUE TITLE
Modify intermediate representation to support language tags for metadata field values

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#173]
Requirements:
- [x] add language of property values to IR (Look at IIIF for multilingual modeling in JSON v2 or v3? https://iiif.io/api/presentation/3.0/#44-language-of-property-values ) 
- [x] write macro to manually assign language values to each field  (e.g. `to_field 'cho_creator', extract_oai('dc:creator'), lang('ara')`
- [x] write test to ensure that the language value passed through the config is a valid BCP47 language value

**Comment by mjgiarlo** [comment]
I believe all the components of this work are now done. See the list of issues and commits above.
