### ISSUE TITLE
Write general date normalization macros

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#175]
![Screen Shot 2019-09-23 at 2 09 36 PM](https://user-images.githubusercontent.com/37662787/65463044-d8834980-de0b-11e9-93cb-50c7f4c7ab51.png)

Requirements:
- [x] write function in `dlme-transform/lib/macros/normalize.rb` that takes a date in the form 'yyyy' or 'yyyy, yyyy' as input and returns an array of year values representing a range of time
- [ ] collection level macros will take data in whatever form and convert it to '[yyyy]' or '[yyyy, yyyy]'. Need to write a test to apply to each of these collection level macros to ensure that the output is one of these forms. A validation error should be raised if not.

**Comment by ndushay** [comment]
The "year_array" method is included in PR #245;  Jacob and I will take a look at each collection and determine what additional general date methods are necessary, as well as specific ones.
