### ISSUE TITLE
Normalize AIMS dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#176]
Requirements:
- [x] write macro to take dates in the form `Wed, 06 Jun 2018 09:12:39 +0000: 1` and return [yyyy]
- [x] update `dlme-traject/aims_config.rb` to use the above macro
- [ ] test output to insure it is a list of values in the form yyyy

**Comment by ndushay** [comment]
with PR sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
