### ISSUE TITLE
Normalize American Numismatic Society dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#177]
Requirements:
- [ ] write a macro to take dates in the form  yyyy, yyy, yy, y and return [yyyy]; pad with 0s if necessary
- [ ] update `dlme-traject/numismatic_csv_config.rb` to use the above macro
- [ ] test output to insure it is a list of values in the form yyyy

**Comment by ndushay** [comment]
After #245 is merged, I would:

- I would select the field via normal traject approach (as it is now)
- create a macro to 
  - take the value in the accumulator
  - split the field value on '|' 
  - send the two values on to the year_array method
- Write tests for new numis macro (add to date_parsing_spec).

then follow the last 2 steps as above.
