### ISSUE TITLE
Normalize AUB dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#178]
Requirements:
- [ ] all of the AUB collections are not in yet but so far dates come in the form yyyy or yyyy-yyyy. Update dlme-traject/aub_config.rb to map to a year array.

**Comment by aaron-collier** [comment]
Per our discussion of not using `earliest` and `latest` but using a range, should this be updated @jacobthill

**Comment by ndushay** [comment]
with PRs sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
