### ISSUE TITLE
Modify intermediate representation to support normalized Gregorian and Hijri dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#179]
Currently the application profile specifies one date value `cho_date`.  To implement the Blacklight Date Range plugin, we will need date ranges in a multivalued field of integers that are stored and indexed. An example for a date range from 1950-1960 years: fake_year_tisim: [1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960]. BCE years will be represented as negative numbers.

We also need a field to store Hijri calendar values. 

Requirements:
- [x] add `cho_date_norm` to the IR to store the normalized array of years
- [ ] add `cho_date_hijri` field to the data model

**Comment by jacobthill** [comment]
Requirements: 
- [ ] add new date field `cho_date_norm` to store the normalized date arrays. The current value `cho_date` can still be used to store date values as they exist in the incoming metadata.
- [ ] update the [application profile](https://github.com/sul-dlss/dlme/blob/master/docs/application_profile.md) to reflect these changes

**Comment by aaron-collier** [comment]
Note: IR is defined in https://github.com/sul-dlss/dlme-transform/blob/master/lib/dlme_json_schema.rb
