### ISSUE TITLE
Normalize AUC dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#180]
This metadata is somewhat messy with dates coming in multiple formats, most commonly in the form "1947-11-28". Will likely require multiple iterations.

A possible strategy:
-look for regex dddd-dd-dd; pass through
-look for regex dddd (only); pass through
-look for regex ddd (only); pass through 
-look for regex dddd-dddd; pass through as year range
-look for regex ddd-ddd; pass through as year range
-gsub('ca. ', '')
-look for dddds => ddd(+1)d and drop s
-look for dddd; dddd; dddd; etc., split on ';' and grab first (append'-' and last)

**Comment by ndushay** [comment]
the parse_date gem handles most of this now; let's talk through what is needed.

**Comment by ndushay** [comment]
closing this per PR #309.  If there are problems, we will open a new ticket.
