### ISSUE TITLE
Normalize BnF dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#181]
Requirements:
- [x] take date in the form yyyy, yyyy-yyyy, or yy-- and return [yyyy] or [yyyy, yyyy]
- [ ] update dlme-traject/bnf
- [ ] test output to insure the form is yyyy

**Comment by aaron-collier** [comment]
@jacobthill same as the other ticket, should we rewrite `earliest` and `latest` to a range here?

**Comment by ndushay** [comment]
with PRs sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
