### ISSUE TITLE
Normalize Harvard Dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#183]
-651 of 813 records have the cho_date value
-some files have 3 different date values
-most common form is dddd, but also dddd-dddd, dduu, dddd [dddd]. etc.
-map dates with common pattern, ignore the rest

Requirements:
- [ ] write macro to map common patterns to yyyy values
- [ ] update dlme-traject/harvard_ihp_config.rb
- [ ] test output to insure the form is yyyy

**Comment by ndushay** [comment]
#### Harvard maps

33 records, `fgdc_config`

I think you may want one or more of these dates for the date slider:

- /*/dataqual/lineage/srcinfo/srctime/timeinfo/rngdates/begdate
- /*/dataqual/lineage/srcinfo/srctime/timeinfo/rngdates/enddate
- /*/dataqual/lineage/srcinfo/srctime/timeinfo/sngdate/caldate
 
For example, record G*2000_1785_M6 has `201202` for `/*/idinfo/citation/citeinfo/pubdate` but `1785` for `/*/dataqual/lineage/srcinfo/srctime/timeinfo/sngdate/caldate`

**Comment by ndushay** [comment]
### Harvard maps

PR #254 provides a macro for harvard/maps  fgdc data, and that appears to be the only fgdc data in play.  The macro should work for any fgdc data, however.

**Comment by ndushay** [comment]
### Harvard IHP (Islamic Heritage Project)

816 records, all oai_dc xml

date field is repeatable, non-normalized.   In pure theory, the elements of DC are not ordered, so it is not strictly correct to expect multiple fields to occur in a specific order.  In practice, this is often ignored.

- records seem to have 1-3 date fields
- when Hijri date is supplied, the Gregorian is within square brackets, eg `1322 [1904]`
- some dates have non-numeric chars, e.g.
    - `1317 [1899 or 1900]`
    - `1288 [1871-72]`
    - `1254 [1838 or 39]`
    - `1894.`
    - `1890-`
    - `1886-1887`
    - `1890?].`
    - `1890?]`

conclusion:  
- if there is a date field with exactly four digits and nothing else, use it.
```
990051308450203941.oai_dc.xml
13:            <dc:date>1289 [1872]</dc:date>
14:            <dc:date>1872</dc:date>
17:            <dc:date>1289 [1872]</dc:date>

990051852800203941.oai_dc.xml
7:            <dc:date>[1908]</dc:date>
8:            <dc:date>1908</dc:date>
11:            <dc:date>[1908]</dc:date>

990021024670203941.oai_dc.xml
8:            <dc:date>1891</dc:date>
11:            <dc:date>1891.</dc:date>

990041168950203941.oai_dc.xml
5:            <dc:date>1922]</dc:date>
6:            <dc:date>1922</dc:date>

```

- Next: if there is a date field with exactly "yyyy-yyyy" send it to timetwister and use range
```
990051235950203941.oai_dc.xml
7:            <dc:date>1883-1884</dc:date>
8:            <dc:date>1301 [1883 or 1884]</dc:date>
11:            <dc:date>1301 [1883 or 1884]</dc:date>

990032658860203941_FHCL:2998101.oai_dc.xml
8:            <dc:date>1865-1869</dc:date>
9:            <dc:date>1282-1286 [1865-1869]</dc:date>

990046599690203941.oai_dc.xml
12:            <dc:date>1877-1879</dc:date>
13:            <dc:date>1294-95 [1877-1879]</dc:date>
16:            <dc:date>1294-95 [1877-1879]</dc:date>

```

- Next: ?  Not sure how many records aren't covered by above, and whether we want to bother with them.

```
990021440950203941.oai_dc.xml
7:            <dc:date>1890-</dc:date>
8:            <dc:date>1890?]</dc:date>
12:            <dc:date>1890?]</dc:date>

990023765090203941.oai_dc.xml
7:            <dc:date>1885-</dc:date>
8:            <dc:date>1303 [1885 or 1886]</dc:date>
12:            <dc:date>1303 [1885 or 1886]</dc:date>


```

**Comment by ndushay** [comment]
I wrote this up before the parse_date gem had a lot of zing to it; let's talk through what is needed before running with what I wrote above. The patterns are valid -- it's the "what is the best way to get the date range" that might have changed, as a bunch of these patterns are now handled by ParseDate.range_array.  Also, see #289 re figuring out when it's gregorian vs hijri

**Comment by ndushay** [comment]
Not handling this variant for #289 (see PR #297);  write a separate macro for harvard ihp format:

### Harvard IHP
see #183 (oai_dc) 
when Hijri date is supplied, the Gregorian is within square brackets, eg 
```
    1322 [1904]
    1317 [1899 or 1900]
    1288 [1871-72]
    1254 [1838 or 39]
    1894.
    1890-
    1886-1887
    1890?].
    1890?]
```
BUT: there are multiple dc:date fields ... so it's possible it will be easier to get the two diff calendar values that way
