### ISSUE TITLE
Normalize Palestine Poster Project Archive dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#185]
-12920 of 12920 records have the cho_date value
-all four digit years (dddd), no normalization required

Requirements
- [x] update dlme-traject/pppa_fonfig
- [ ] test output to insure the form is yyyy

**Comment by ndushay** [comment]
with PRs sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
