### ISSUE TITLE
Normalize Princeton dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#186]
Notes:
-3230 of 3240 records have the cho_date value
-most are in the form YYYY or YYYY-YYYY
-one record was "1749 January 5"

Requirements:
- [x] write macro to take in dates as yyyy, yyyy-yyyy, or 1749 January 5 and return [yyyy] or [yyyy, yyyy]
- [x] update dlme-traject/princeton_mss_config.rb
- [ ] test output to insure it is a list of values in the form yyyy

**Comment by ndushay** [comment]
with PRs sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
