### ISSUE TITLE
Normalize QNL dates

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#187]
Dates are in the form of YYYY/YYYY - translate into multivalued range of all years including the start and end year.

Notes:

-16132 of 16132 records have the cho_date value
-all in the form YYYY/YYYY

Requirements:
- [x] update dlme-traject/qnl_config.rb

**Comment by ndushay** [comment]
with PRs sul-dlss/dlme-transform/pull/231 and sul-dlss/dlme-traject/pull/134, this is implemented.
