### ISSUE TITLE
Transformation errors after gem update

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#209]
There are transformation errors with 3 datasets since the gem update: 'cambridge', 'penn', and 'stanford'. Not sure if they are related. Running transformations locally on each of the collections should reproduce the errors. Let me know if there are any issues reproducing the errors. The penn error may be related to https://github.com/sul-dlss/dlme-transform/issues/161

**Comment by aaron-collier** [comment]
@jacobthill can you include some of the error information you're seeing so we can verify what we see locally?

Thank you.

**Comment by jacobthill** [comment]
I’m away from my computer until tomorrow but as I recall penn was an error related to tie_config, stanford was related to mods_config and cambrige was a dry validation error. I’ll post the actual error messages in the morning

**Comment by jacobthill** [comment]
stanford error: ```[ERROR] Error loading configuration file config/mods_config.rb:28 ArgumentError:wrong number of arguments (given 2, expected 1)
/usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer.rb:231:in `rescue in block in load_config_file': Error loading configuration file config/mods_config.rb:28 ArgumentError:wrong number of arguments (given 2, expected 1) (Traject::Indexer::ConfigLoadError)```

penn error: ```[ERROR] Error loading configuration file config/tei_config.rb:46 ArgumentError:wrong number of arguments (given 2, expected 1)
/usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer.rb:231:in `rescue in block in load_config_file': Error loading configuration file config/tei_config.rb:46 ArgumentError:wrong number of arguments (given 2, expected 1) (Traject::Indexer::ConfigLoadError)```

cambridge error: ```[ERROR] Transform produced invalid data.
The errors are: [#<Dry::Schema::Message text="must be filled" path=[:agg_is_shown_at, :wr_id] predicate=:filled? input="">, #<Dry::Schema::Message text="must be filled" path=[:agg_preview, :wr_id] predicate=:filled? input="">]}```

**Comment by aaron-collier** [comment]
Thanks @jacobthill. It appears that this may all be related to the issues @mjgiarlo is discussing in channel. Hopefully we'll get this addressed quickly.

**Comment by jacobthill** [comment]
I think the penn and stanford errors are related to what @mjgiarlo is working on; I think the cambridge errors are caused by something else.

**Comment by aaron-collier** [comment]
Oh yeah, that's the dry work that @ndushay is working through. Should be addressed soon. Thank you for the detail.

**Comment by ndushay** [comment]
stanford:

E, [2019-09-26T22:24:01.273546 #8] ERROR -- : IIIF Manifest not found: Unexpected response type 'text/html; charset=utf-8' for https://purl.stanford.edu/18020021/iiif/manifest
...
E, [2019-09-26T22:24:01.500964 #8] ERROR -- : IIIF Manifest not found: Unexpected response type 'text/html' for https://purl.stanford.edu/bh691yj7263/iiif/manifest
...
E, [2019-09-26T22:24:01.578567 #8] ERROR -- : IIIF Manifest not found: Unexpected response type 'text/html' for https://purl.stanford.edu/bm840kw7224/iiif/manifest
```

**Comment by ndushay** [comment]
I can confirm that we have worked through the dependency update issues both for [traject, traject_plus] and for [dry-schema, dry-validation]
