### ISSUE TITLE
Improve integration testing to include dlme-traject

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#221]
Add a task to circle ci to exercise the docker dlme-transform docker task with select (or all) of the dlme-traject based configurations in order to avoid update based breaking changes.

**Comment by mjgiarlo** [comment]
@aaron-collier Can we chat tomorrow about what testing strategy to use for this? I can't recall what decisions we may have made about this already. Should we, say, parse `metadata_mappings.json` and loop over the mappings, grabbing a number of records from each config? That way we can be sure to touch all relevant configs, without hard-coding them in the testing machinery. How records per config are enough?

Tagging @jacobthill too.

**Comment by mjgiarlo** [comment]
@jacobthill @aaron-collier Now that https://github.com/sul-dlss/dlme-transform/pull/262 is close to moving forward, I'd like to hear your thoughts on:

> Should we, say, parse `metadata_mappings.json` and loop over the mappings, grabbing a number of records from each config? That way we can be sure to touch all relevant configs, without hard-coding them in the testing machinery. How many records per config are enough?

**Comment by jacobthill** [comment]
@mjgiarlo that was my understanding of the plan. It makes sense to me given that the data, configs, etc. are constantly changing
