### ISSUE TITLE
Fix traject deprecation warnings

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#224]
When attempting to transform stanford data locally, a number of deprecation warnings related to traject appear. 

To reproduce, run locally:
```docker run --rm -e SKIP_FETCH_CONFIG=true \
                -e SKIP_FETCH_DATA=true \
                -v $(pwd)/.:/opt/traject \
                -v $(pwd)/../dlme-traject:/opt/traject/config \
                -v $(pwd)/../dlme-metadata:/opt/traject/data \
                -v $(pwd)/output:/opt/traject/output \
                suldlss/dlme-transform:latest \
                stanford

**Comment by aaron-collier** [comment]
Note, these deprecations are coming from the `normalize_language` and `normalize_script` mods macros.

**Comment by jacobthill** [comment]
Okay, may we can hold off on this for now. I think we will not need those once https://github.com/sul-dlss/dlme-transform/issues/144 is complete. We may be able to delete them.

**Comment by aaron-collier** [comment]
the above is related to language codes (only in stanford_mods as far as I can tell), the only file without a language code at all is:

rz546pm0247.mods
