### ISSUE TITLE
upgrade to traject_plus 2.0

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#230]

**Comment by mjgiarlo** [comment]
@jacobthill This is going to require changing many (?) of the Traject configs in dlme-traject. Can you say more about what is driving this? Other than, of course, keeping pace with upgrades to avoid falling behind too far. cc: @aaron-collier

**Comment by aaron-collier** [comment]
@mjgiarlo I think this is going to be a bigger ticket (or tickets). The gist is that we need to identify what all of those many changes are.

**Comment by mjgiarlo** [comment]
Some of the changes that will be required:

1. TrajectPlus 2.0's implementation of `extract_xml` (which underlies `extract_mods`, `extract_tei`, and `extract_fgdc`) uses Traject's `extract_xpath` which does not allow keyword args. That means all the dlme-traject configs that call `extract_mods` with keyword arguments (such as `translation_map`) will break, and we'll need some other mechanism for applying macro-specific translation maps. Not sure how to do this in a Traject 3 pipeline-y way.
1. Also, `extract_xpath` in Traject returns a lambda with an arity of 2 (https://github.com/traject/traject/blob/master/lib/traject/macros/nokogiri_macros.rb#L20), and some of TrajectPlus's macros---like `first` and `conditional`: https://github.com/sul-dlss/traject_plus/blob/master/lib/traject_plus/macros.rb#L24-L48---assume lambdas or arity 3. Either we'd need to rejigger these functions in TrajectPlus, make `extract_xpath` in Traject work with arity 3 lambdas, or rewrite our configs to stop using these TrajectPlus macros (in a more Traject 3 pipeline-y way, whatever that means).

cc: @aaron-collier @jacobthill @jcoyne
