### ISSUE TITLE
Normalize Michigan dates

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#263]
Some combination of getting 008 from marcxml,  getting only bytes 6-14 (0 based) into the accumulator, then applying marc_date_range.

It looks like this for marc21 data (but not for marcxml):

```
    to_field "cho_date_range_norm", extract_marc("008[06-14]"), marc_date_range
```

**Comment by ndushay** [comment]
I have a branch michigan for this, after PR #271 is merged. The actual output would need to be vetted by Jacob, but my cursory glance looked good.  It bumped into a record that had bad data, but it ran smoothly for a lot of records prior to that.
