### ISSUE TITLE
Update config files to map to revised IR

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#266]
Once the IR is revised https://github.com/sul-dlss/dlme-transform/issues/173, adjust the config files to map to new data fields

**Comment by mjgiarlo** [comment]
@jacobthill @aaron-collier Is this ticket waiting on a dev to pick it up or is this a ticket for @jacobthill?

**Comment by aaron-collier** [comment]
I believe this was something @jacobthill intended to do, but we're likely at a point where a dev passing over the fields would be sufficient as I think each of the configs have been touched and updated as part of the internationalization and date work. A few one-offs may need to be updated, but it wouldn't surprise me if this closable.

**Comment by jacobthill** [comment]
I think this is covered in the Epic and collection level tickets @aaron-collier created yesterday. It can be closed.
