### ISSUE TITLE
Refactor Macros::DateParsing into sub-modules

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#283]
This single module has gotten pretty long and should be refactored into individual single responsibility sub modules.

**Comment by ndushay** [comment]
meh.

**Comment by mjgiarlo** [comment]
@aaron-collier I'm meh on this as well. In this case, I am in favor of deferring refactoring until a better abstraction presents itself. Backlog/close?

**Comment by aaron-collier** [comment]
I'm OK with just keeping this backlogged. It's certainly not a priority, but I'd like to keep it as tech debt. I'll tag and backlog.

**Comment by ndushay** [comment]
probably will be taken care of (at least for now) with PR for issue #291, as it greatly shortens the date_parsing.rb file.

We could also put these into parse_date gem, if we want:
- to_hijri
- hijri_range

then existing hijri_range macro would be a simple call to ParseDate.hijri_range, and to_hijri macro would go away ...
