### ISSUE TITLE
Check, revise, and transform all collections

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#290]
After significant changes to the IR, it is necessary to check, possibly revise, re-transform, and re-load all data sets.

Data sets:
- [x] AIMS
- [x] American Numismatic
- [x] AUB
- [x] AUC
- [x] BnF
- [x] Bodleian
- [x] Cambridge
- [x] Cluster
- [x] Harvard
- [x] Met
- [x] Michigan
- [x] Palestine Posters
- [x] Penn
- [x] Princeton
- [x] QNL
- [x] Sakip Sabanci
- [x] Stanford

**Comment by aaron-collier** [comment]
Captured in individual tickets and an epic to track all 17.
