### ISSUE TITLE
Catch exception where first year > last year

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#325]
The parse_date gem raises an error in this case, but for AUC (and likely other collection) we want to capture this error and log it as a warning in order to fix at the provider.

**Comment by ndushay** [comment]
... and use value nil and go on to the next record.

do something to make the error stand out in the traject output ... ?

**Comment by mjgiarlo** [comment]
@aaron-collier @ndushay @jacobthill I was unable to reproduce any exceptions when running a transform against the entire AUC dataset via `exe/transform --data-dir auc`. Does that mean we can close this issue? If there's something else I should be doing to reproduce this error before trying to fix it, that'd be good to include as details on this issue. Thanks!

**Comment by ndushay** [comment]
dude - i found it.  In PR by @mjgiarlo :  https://github.com/sul-dlss/dlme-metadata/pull/123

coll:  penn/near-eastern/data/egyptian-20181028-cleaned.csv
