### ISSUE TITLE
Dry schema validation errors

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#329]
Trying to assign language values to some fields is causing dry schema validation errors. 'cho_title', 'agg_provider', 'agg_data_provider', 'agg_provider_country', 'agg_data_provider_country' work as expected. 

'cho_edm_type', 'cho_has_type', 'cho_language' , 'cho_description', 'cho_date', 'cho_creator', 'cho_date_range_norm', 'cho_date_range_hijri', 'cho_dc_rights', 'cho_extent', 'cho_alternative', 'cho_contributor', 'cho_coverage', 'cho_format', 'cho_has_part', 'cho_is_part_of' 'cho_medium', 'cho_provenance', 'cho_publisher', 'cho_spatial', 'cho_temporal' 'cho_type' need these changes as well.

**Comment by ggeisler** [comment]
@jacobthill I think we will need the language info for metadata fields so that we can try to show the version of the field (when a field has multiple language versions) that matches the user's current locale.

So that seems like reason alone to want to assign language values to fields?

**Comment by jacobthill** [comment]
@ggeisler thats what I was thinking, thanks for confirming.

**Comment by mjgiarlo** [comment]
@jacobthill When you're making a new field multi-lingual, there are two changes you need to make to the `Contracts::CHO`:

1. Change the data type validation from its original value (like `.array(:str?)`) to `.value(:hash?)` (See [example](https://github.com/sul-dlss/dlme-transform/blob/master/lib/contracts/cho.rb#L34))
2. Add a new rule using the existing field. (See [example](https://github.com/sul-dlss/dlme-transform/blob/master/lib/contracts/cho.rb#L84))

One wrinkle: the lang-specific rule currently **also** validates that the field has values (*i.e.*, it's for required fields). I can add a new method for use in optional lang-specific fields that you can use. Once that's done... say you are multilingualizing `cho_extent`, for step two above, you'd add `rule(:cho_extent, &optional_language_specific_rule)`
`

**Comment by jacobthill** [comment]
@aaron-collier I still need to add all of the other fields.

**Comment by aaron-collier** [comment]
Moved to #336
