### ISSUE TITLE
Empty lang hash created when no field value found

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#365]
the `to_field` method in traject returns nothing when nothing is found in the raw data. e.g. `to_field 'cho_contributor' extract_oai('dc:contributor')` will return nothing if the raw value doesn't have a 'dc:contributor' element. When we assign a language value `lang('en')` and convert to hash `each_record convert_to_language_hash('cho_contributor')` a hash with an empty array is returned e.g. `"cho_contributor": {"en": []}`

The cho_contributor and cho_creator fields in AUB data once https://github.com/sul-dlss/dlme-transform/pull/364 is merged.

**Comment by ndushay** [comment]
This is true for some records in `aub/aladab` only:

```bash
docker run --rm -e SKIP_FETCH_DATA=true -v $(pwd)/.:/opt/traject -v $(pwd)/../dlme-metadata:/opt/traject/data -v $(pwd)/output:/opt/traject/output suldlss/dlme-transform:latest aub/aladab/data/1.xml
```

```json
{
"cho_contributor":{"ar-Arab":[]},
"cho_creator":{"ar-Arab":[]},
"cho_subject":{"ar-Arab":[]}
```
