### ISSUE TITLE
Add field to support hierarchical facet display

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dlme-transform#383]
In order to support the hierarchical facet described in sul-dlss/dlme#552 we need a field that has the the entire hierarchy expanded and delimited with a consistent value (that will not be in the data). You can see an example of the expected solr fields to support the hierarchy in the [Usage section](https://github.com/sul-dlss/blacklight-hierarchy#usage) of the blacklight-hierarchy gem.

I'm not 100% sure which two fields are intended to be included in the hierarchy.  I see `cho_edm_type_ssim` (the current Type facet) and `cho_type_ssim` (which is listed as the Other type facet, but I haven't seen it in any data yet).  So this might be something that needs a bit of clarification if we don't have the data to support this display yet.

**Comment by ndushay** [comment]
- `cho_type_facet` - field name
- cho_edm_type:cho_has_type  value -- that is, the field will be the value of cho_edm_type followed by a colon followed by cho_has_type value.
- the facet is also a language tagged field, we think <-- @jkeck ?
- the easiest way will be to add a method to `each_record` macros that uses `_context` to get existing field values and combine them into the new field values

**Comment by jkeck** [comment]
> the facet is also a language tagged field, we think

👍 We will need that in order to have the hierarchical facet be translated when the user changes the language of the application (which is the desired outcome).
