### ISSUE TITLE
Fix NOT FOUND debugging tool

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#409]
When mapping to a normalized value such as cho_language or cho_edm type if a value is not found in any translation map, the value 'NOT FOUND' is stored in the field and an error should be raised when that problematic record is transformed, breaking the transform process and returning the record data so the error can be fixed. This used to work and is now broken. We need to get it up and running again.

**Comment by jacobthill** [comment]
This is blocking https://github.com/sul-dlss/dlme-transform/issues/408

**Comment by aaron-collier** [comment]
The configuration is in place: https://github.com/sul-dlss/dlme-transform/blob/master/lib/contracts/cho.rb#L17 However, I wonder if the syntax is the issue as we've seen in the past. @jacobthill do you have a data set that can be used when testing this?

**Comment by jacobthill** [comment]
I don't know where an actual record is at the moment that is raising this but an easy trick to try would be to put this line in the config:
```
to_field 'cho_language', literal('this is not a language and will not be found in any translation map'), normalize_language, lang('en')
```
That should raise an error on the first record.
