### ISSUE TITLE
Raise error when no cho_title present

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#413]
cho_title is a required field and an error should be raised if it is missing. Somehow 29 records in the cambridge collection passed transformation without raising an error. 

https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-4c2913b0-f254-487d-b43b-fc866adb2e85.ndjson

**Comment by aaron-collier** [comment]
@jacobthill Do you have identifying information about the 29 records? I'm having difficulty finding anything blank in the IR.

**Comment by jacobthill** [comment]
Here is the id of one record `cambridge_genizah-11061`. I think if you find that one and then search for the string in the cho_title field you will find all 29. This is an interesting case. I'm mapping currently and an error is raised when cho_title is not found. I think this passed our tests because cho_title is there; it just happens to be empty. I think the desired behavior is a field doesn't make it into the IR if it is empty which would trigger the no_title error.

**Comment by aaron-collier** [comment]
Thank you, that should help.
