### ISSUE TITLE
Revise Michigan config

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#415]
- cho_description was causing errors, currently commented out
- not sure if cho_spatial is mapping the right fields

**Comment by jacobthill** [comment]
@ndushay Do you have a moment to assist with this? It was merged but the cho_description field is causing validation errors. I'm not sure how to fix it.

**Comment by aaron-collier** [comment]
@jacobthill the description was fixed in #441 - can you verify if the spatial issues are still valid?

**Comment by jacobthill** [comment]
Closing via https://github.com/sul-dlss/dlme-transform/issues/494 and https://github.com/sul-dlss/dlme-transform/issues/495
