### ISSUE TITLE
Provide links to the IIIF manifests when known

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme-transform#423]
Blocking https://github.com/sul-dlss/dlme/issues/734 (or, at least, blocking the display of these things)

The source IIIF manifest should be recorded in the  IR when we have it - either directly from the source metadata, or in cases where it's fairly predictable and can be mapped(e.g., we know how to get to a manifest from a Stanford PURL (and this seems to be the [only case this mapping was done](https://github.com/sul-dlss/dlme-transform/blob/9f4bcee192ef990a0d85094b96d8f863c10d64a3/traject_configs/stanford_mods_config.rb#L32)). 

There's a note about how to do with in EDM profiles in the mapping in §1.5 of https://pro.europeana.eu/files/Europeana_Professional/Share_your_data/Technical_requirements/EDM_profiles/IIIFtoEDM_profile_042016.pdf.

**Comment by aaron-collier** [comment]
Closing as this work is in progress per collection.
