### ISSUE TITLE
Script detection macro

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#430]
Any title, creator, contributor etc. in Latin characters will have one or more Latin vowels. A simple script detection macro can be designed by checking strings for the presence of a vowel. This can be used to improve language tagging, especially in the case of Arabic titles in Latin script and Arabic titles in Arabic script.

**Comment by aaron-collier** [comment]
It would be worth investigating if there are any supported gems that may do this for us so that we're not limiting the results. I'll do a bit of testing today and we can discuss the results after the break.

**Comment by jacobthill** [comment]
That makes sense. I've been using this approach in harvesting Princeton data because their language tags are inconsistent and it seems to work quite well.

**Comment by aaron-collier** [comment]
The CLD gem seems initially accurate on some of our stuff:

```
irb(main):001:0> require 'cld'
=> true
irb(main):002:0> CLD.detect_language("This is a test")
=> {:name=>"ENGLISH", :code=>"en", :reliable=>true}
irb(main):003:0> CLD.detect_language("هولندي؛ الفلمنكية")
=> {:name=>"ARABIC", :code=>"ar", :reliable=>false}
irb(main):004:0> CLD.detect_language("slovakça")
=> {:name=>"TURKISH", :code=>"tr", :reliable=>false}
```

I'll try it on larger data sets.

**Comment by jacobthill** [comment]
@aaron-collier language detection is a much harder task than what I'm proposing and it is really error prone on things like names and titles (where we need it). I think if we can detect the script only that will be more accurate and much simpler.

**Comment by jacobthill** [comment]
Added this in python mapping analysis scripts.
