### ISSUE TITLE
Don't pass through raw translation values if none match.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme-transform#45]
Please provide:
What steps should I take to duplicate this problem?
What is the incorrect behavior you are seeing?
What is the correct behavior you want to see?

**Comment by jacobthill** [comment]
I need to write the config files for sakib-sabanci collections wish will include a line like ```to_field 'cho_language', extract_xml("#{record}/dc:language", LOC_NS), first_only, strip, translation_map('marc_languages')``` This line will pull nothing from the translation map because the values in the metadata (e.g. <dc:language>Türkçe</dc:language>) are not it there. So, it will pass along Türkçe, resulting in the values 'Türkçe' and 'Turkish' both existing in the index. These values should be normalized so that only Turkish shows up.

**Comment by jcoyne** [comment]
@jacobthill can you provide an example of the command you are running? In the standup you mentioned flagging the record. What does that look like?

**Comment by jacobthill** [comment]
I just mean when the config file is processed, if the language value in the metadata record is not found in the translation map, some alert or error should occur instead of the default being to pass the value through as is. I can then add the value found to the translation map or pass a literal value so that we don't end up with multiple values in the database that refer to the same language.

**Comment by justinlittman** [comment]
@jacobthill Clear, but an example of the command you are running would be really helpful.

**Comment by jacobthill** [comment]
@justinlittman I'm not running any commands yet because I haven't written the sakip-sabanci configs yet. Those are the files that will have this issue. There might be others but I haven't seen any yet that I can point you to. As soon as I write those, I'll send along the command.

**Comment by justinlittman** [comment]
Super!

**Comment by anarchivist** [comment]
blocked until @jacobthill can requested info

**Comment by jacobthill** [comment]
https://github.com/sul-dlss/dlme-traject/pull/9 shows the problem. the values are not in the types translation_map or the language translation_map so the default value is returned (if default is called, else nothing is returned). What I would like to see is an error message when the translation_map doesn't have the value from the raw data so I can add it and ensure that all values are normalized as they should be.

**Comment by justinlittman** [comment]
I can think of 2 approaches:
1. Use a default like NOT_FOUND and then have the validation make sure that the value isn't NOT_FOUND.
2. Create our own validation map subclass that requires a match and raises an error if not.

I'm inclined toward 1 because validation isn't something that traject configs otherwise do.

Thoughts @jcoyne ?

**Comment by jcoyne** [comment]
@justinlittman another approach would be to have TranslationMap raise an error if the key is not found.  Would that cause trouble with out error reporter?

**Comment by justinlittman** [comment]
@jacobthill Here is the proposed solution:

In the config for `cho_language`, you set a default of `NOT FOUND`, like:
```
to_field 'cho_language', extract_xml("#{record}/dc:language", NS), first_only,
         strip, translation_map('marc_languages'),
         default('NOT FOUND')
```

When you run with DebugWriter, you see:
```
http://digital.sabanciuniv.edu/abidindino/mektup/3040200000988.pdf cho_language              NOT FOUND
```

When you run with DlmeJsonResourceWriter, you get:
```

```
[ERROR] Transform produced invalid data.

The errors are: {"cho_language"=>{0=>["must not be one of: NOT FOUND"]}}

The data looked like this:
{
  "cho_title": [
    "Kandilli, 13 Haziran 1979 tarihli Abidin Dino'ya mektup."
  ],
  "cho_language": [
    "NOT FOUND"
  ],
  "cho_description": [
    "Bodrum - Fethi Naci - Ferit Edgü - Vakko - Vitali Hakko - Leyla Umar - \"Cumhuriyet\" - Rasih Nuri İleri. Mektup."
  ],
  "cho_dc_rights": [
    "© Sabancı Üniversitesi Sakıp Sabancı Müzesi. Tüm hakları saklıdır."
  ],
  "cho_format": [
    "pdf"
  ],
  "id": "http://digital.sabanciuniv.edu/abidindino/mektup/3040200000988.pdf",
  "agg_data_provider": "Sakip Sabanci Museum",
  "agg_provider": "Sakip Sabanci Museum"
}
```

How does this work? Is `cho_language` the only field that this would apply to?

**Comment by jacobthill** [comment]
@justinlittman I think that will work. We will need the same solution for cho_edm_type

**Comment by jacobthill** [comment]
@justinlittman Is there a way to change the error message to pass the raw data that was not found in the translation map as well? This would make it easier to debug. I wouldn't have to hunt through the metadata to find the values that aren't in the translation map yet.

**Comment by jacobthill** [comment]
Also how will this deal with cases in which there is no language or type value in the raw data? It seems like it will pass through the default value 'NOT_FOUND' resulting in an error.

**Comment by justinlittman** [comment]
OK, so with:
```
to_field 'cho_language', extract_xml("#{record}/dc:language", NS), first_only,
         strip, translation_map('not_found', 'marc_languages')
```

you get:
```
http://digital.sabanciuniv.edu/abidindino/mektup/3040200000988.pdf cho_language              NOT FOUND | Türkçe
```
and:

```
The errors are: {"cho_language"=>{0=>["must not be one of: NOT FOUND"]}}

The data looked like this:
{
  "cho_title": [
    "Kandilli, 13 Haziran 1979 tarihli Abidin Dino'ya mektup."
  ],
  "cho_language": [
    "NOT FOUND",
    "Türkçe"
  ],
```

**Comment by jacobthill** [comment]
@justinlittman that works for me. Can we do the same thing with cho_edm_type?
