### ISSUE TITLE
Some transformed records not displaying

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#474]
![Screen Shot 2020-02-10 at 1 27 30 PM](https://user-images.githubusercontent.com/37662787/74178266-3ffa3400-4c09-11ea-992e-6d2f8c7d67ef.png)

![Screen Shot 2020-02-10 at 1 27 51 PM](https://user-images.githubusercontent.com/37662787/74178273-412b6100-4c09-11ea-982a-4e888923f1e8.png)

Not all of the records were added. We did some work during the last work cycle to allow collections to continue processing when there was a data error in one or more records. There were cases where the end date was earlier than the start date, for example. Rather than allowing these kinds of errors to break the transform the intended behavior should be to skip the field with the data error. Its possible that the actual behavior is to skip the whole record. This is one possible reason for the discrepancy in numbers.

**Comment by jacobthill** [comment]
Update: Qatar National Library seems to have the same problem on a much larger scale. 17,259 records were transformed but only 5,457 records were added.

**Comment by aaron-collier** [comment]
I'm thinking this may be more about making a report that shows problems than actually getting through the records. This should be one of our discussion topics (I think it may already be) for the meeting.

**Comment by jacobthill** [comment]
That makes sense to me.

**Comment by anarchivist** [comment]
To confirm the initial analysis, it looks like this case that 22308 is the number of records in the source, but there are only 20659 in the file.

```
$ jq -s length output-fbc96a9d-734d-40e8-968f-36d1c113c9af.ndjson
20659
```

**Comment by jacobthill** [comment]
Just reloaded the Cambridge data one set at a time to see if I could narrow down the problematic records and they all loaded in. I'm not sure what caused this glitch but the Cambridge records seem to be working. The other three are all related to the agg_preview field. If the field is empty or the value is an invalid url, the records don't show up. I'm waiting for some PRs to merge to see if this completely resolves the problem or only partially.

**Comment by anarchivist** [comment]
@jacobthill Thanks. I ran the transform locally and saw the same total as you.

**Comment by jacobthill** [comment]
Closing via https://github.com/sul-dlss/dlme/issues/866
