### ISSUE TITLE
Detect script/characeter set from text of title and use it to call another macro to add language info to the title field

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dlme-transform#532]
We need to examine the characters that exist in the title of an incoming record and use this to pass to a method to set the script-language pair.

e.g. a macro that takes a record as input and returns the script type as an output as shown here: https://github.com/sul-dlss/dlme-transform/pull/531

and then call the existing `lang()` macro with the result, like here but dynamically: https://github.com/sul-dlss/dlme-transform/pull/531/files#diff-b1586f1b2ce8cc5cd2e78648ee99c792R37

so that `cho_title` has the language info

**Comment by peetucket** [comment]
To test transform:

```
docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VCS_URL=`git config --get remote.origin.url` \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             . -t suldlss/dlme-transform:latest
```

Run sample file through:
```
docker run --rm -e SKIP_FETCH_DATA=true \
                -v $(pwd)/.:/opt/traject \
                -v $(pwd)/../dlme-metadata:/opt/traject/data \
                -v $(pwd)/output:/opt/traject/output \
                suldlss/dlme-transform:latest \
                princeton/princeton-mss/data/princeton-mss-1.json
```

**Comment by peetucket** [comment]
[princeton-mss-1.json.zip](https://github.com/sul-dlss/dlme-transform/files/4405813/princeton-mss-1.json.zip)

**Comment by ndushay** [comment]
Questions for Jacob:
- does all the princeton data have these tags in their title field?
- how many language tag values are there in the princeton data (e.g. is there 2 values?  1 value? 5 values?)
- do we need to detect the script in this manner?  (a short string is not always the most accurate for this)
- how does the script relate to the language tags that were implemented in a whole diff way -- is that completely separate from this need?

**Comment by jacobthill** [comment]
I believe this problem is solved https://github.com/sul-dlss/dlme-transform/pull/531 but waiting on review

**Comment by peetucket** [comment]
We got an approval, feel free to merge #531 and move forward
