### ISSUE TITLE
Load relevant translation maps into Transifex 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/dlme-transform#535]
dlme-transform's YML files will require a little bit of wrangling to load into Transifex. Some of these mappings only provide English values implicitly (i.e. in the key name, `Book: كتاب`). Transifex interprets that as an absence of source language values. 

Example: https://github.com/sul-dlss/dlme-transform/blob/master/lib/translation_maps/norm_has_type_to_ar.yaml

Here's an example of a `YAML_GENERIC` config example from their support team:
https://gist.github.com/camillevilla/71b3e103e022afd2d62689f9fb6c549b

There are a couple of ways to approach this. It would be ideal if we were able to do this in a way that still took advantage of the GitHub integration, but manual upload of files is acceptable.

**Comment by camillevilla** [comment]
4/6: Clarified with @jacobthill at standup. The only relevant files for this translation project are: 
- https://github.com/sul-dlss/dlme-transform/blob/master/lib/translation_maps/norm_has_type_to_ar.yaml
- https://github.com/sul-dlss/dlme-transform/blob/master/lib/translation_maps/norm_languages_to_ar.yaml

We basically need a YML file that says `Book: Book`. Up to folks re: whether to persist this file in GitHub or create as part of a manual workflow.

**Comment by jacobthill** [comment]
And https://github.com/sul-dlss/dlme-transform/blob/master/lib/translation_maps/norm_types_to_ar.yaml
