### ISSUE TITLE
Write version of DebugWriter

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#65]
We need to write our own version of DebugWriter. There is an error in LineWriter https://github.com/traject/traject/pull/202 that is causing problems when trying to run on a directory of files. I use DebugWriter to check that the transformations I'm making are doing what they are supposed to. I understand that DebugWriter will not check the IR. I will use JsonWriter for that once I'm happy with the transformations.

**Comment by justinlittman** [comment]
Also, would be helpful to have DebugWriter as a commandline flag so that don't need to change writer in config.
