### ISSUE TITLE
Test arrays in IR for duplicate values

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#677]
As the DLME data manager I need to ensure that no records are loaded with duplicate values in any field. Most fields contain hashes with language keys and arrays as values (e.g. `"cho_title":{"en":["Incipit Page with Illuminated Headpiece"]}`). Some fields contain only arrays (e.g. `"cho_identifier":["W.651.1B","W6511B"]`). In all cases, the values in the array should be testes to ensure that no two values are identical.

Requirements:
- [ ] Fails if duplicate values found in any array; the transform process will stop and an error message with problematic field, values, and dlme_source_file will be reported to the terminal.

**Comment by jacobthill** [comment]
Maybe this should not fail and stop transform when duplicate values are found. Duplicate values could come from data errors or transform errors. In the case of data errors we simply want to remove the duplicate value. In the case of transform errors we want to fix the error in the config so we aren't adding duplicate values to the IR. I'm not sure how to solve this problem. We could simply remove all duplicate values and ignore the possibility that the error may have come from our configs. Or maybe there is a more intelligent way to do this with the -w flag?

**Comment by jmartin-sul** [comment]
@jacobthill question just to make sure i'm clear on the desired behavior:  you want this de-duplication to apply to all arrays in all fields, correct?  as opposed to doing this for specific fields?  do you see any need to omit known fields from this de-duplication (i.e., are duplicate entries in arrays ever expected and valid)?

@aaron-collier or @jacobthill, could you say more about how the `-w` flag might be used for implementing this duplicate spotting?  i'm still pretty unfamiliar with traject, and from reading the docs, it seems like that allows specification of a custom writer... so would we implement or modify a writer that does the de-duping, and invoke that?

**Comment by jacobthill** [comment]
Yes, that is correct. No field should ever have duplicate values. We want to remove them from all fields. We also want to notice and correct instances when duplicate values are caused by an error in our configs, hence the -w flag option (I'm not sure if this is the way to go but it is the pattern already available in traject so worth considering). @aaron-collier might know better about your implementation question. My understanding is that the debug writer is used when the -w flag is called which only changes what is written to the terminal and also should stop upon encountering an error. I'm confused about how it works in practice though. For example, the harvard/scw collection doesn't normalize all dates. I would expect the -w flag to stop upon encountering a record with a date that can't be normalized but it doesn't. Maybe we can review this today at our story time or after stand up.
