### ISSUE TITLE
Loading data in prod not working

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#685]
Adding items in prod https://dlmenetwork.org/library/resources/new doesn't work. I get a confirmation that is was added to the queue but the records never load. I'm using this data set:

https://s3-us-west-2.amazonaws.com/dlme-metadata-dev/output-88068304-405b-41fe-aaac-45a8e15162db.ndjson

**Comment by aaron-collier** [comment]
I'm not sure how to debug or verify this. The logs for the indexing job show as running without error, so some items are at least getting indexed.

**Comment by aaron-collier** [comment]
Also:

https://dlmenetwork.org/library/catalog?f%5Bindexed_at%5D%5B%5D=day

Shows 142k works indexing within the last day... so _something_ is getting in. 

@jacobthill can you confirm that no works are getting in from _any_ data set or is it just this data set?
