### ISSUE TITLE
Add honeybadger to dlme-transform

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#750]
We currently only have logging and no method of notification on failure. If a transformation fails, or has any errors, the way to determine that would be to review the large logs on Cloudwatch, by alerting via honeybadger we can better indicate individual record failures during the transform step.

**Comment by jermnelson** [comment]
@aaron-collier quick question; to add HB do we want take Sinopia's [approach](https://github.com/LD4P/sinopia_editor/blob/774a4b20c2ad7546f109380e01a2561bf93657be/.circleci/config.yml#L108) and add the HB API to the circle-ci build or do think we add the HB yml file to shared_configs?

**Comment by jmartin-sul** [comment]
closed by #761 (which built on #754)
