### ISSUE TITLE
Bad urls should not break application

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#759]
Currently if a bad url is loaded in the agg_preview field (probably agg_is_shown_at as well), the following error message is displayed when clicking on the set of records containing the bad url (e.g. through selecting the data contributor): 
<img width="667" alt="Screen Shot 2020-08-21 at 9 20 28 AM" src="https://user-images.githubusercontent.com/37662787/90895103-9d78f580-e38f-11ea-9192-424384edb1c8.png">
Selecting `exhibit dashboard` to unload the records results in the same message.

Loading bad urls is part of the transformation process. I have error checking locally but it only tests if the url is valid not if it is resolvable. I also forget to run that check sometimes. In some cases, particularly when the collection is large, it is difficult to find the record with the bad url. 

Desired behavior:
- [ ] The application will not break completely when a bad url is loaded; it should still be possible to access the `exhibit dashboard` to unload the records.
- [ ] The error message will indicate that the url will not resolve and return the `dlme_source_file` value (if available) and the id instead of "We're sorry, but something went wrong."

**Comment by aaron-collier** [comment]
An option for this issue may be to expand or enhance the validation around web resources to include a check that they resolve: https://github.com/sul-dlss/dlme-transform/blob/main/lib/contracts/cho.rb#L125

**Comment by jacobthill** [comment]
This is captured in the google doc, but maybe first we should check to see if they are valid. I'm pretty sure the application doesn't break when a url doesn't resolve as long as its valid. It seems to only break when you pass something that doesn't look like a valid url. The other issue, of course, is when we re-harvest a set we should test urls and suppress those that no longer resolve so we keep the site clean or broken urls.

**Comment by aaron-collier** [comment]
@jacobthill I ran a test on the QNL data where we do not add the `agg_preview` if there isn't a manifest, this has resolved the breaking issue after re-transforming/indexing.

However - as stated elsewhere I think this is only a half measure. For discussion, what do we want to include in agg_preview (if anything) when there is no thumbnail URL or it is invalid?
