### ISSUE TITLE
Add dlme_collection field 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#798]
- [ ] add dlme_collection field to application profile
- [ ] make it a mandatory field, it will be used as a collection identifier
- [ ] use a controlled vocabulary to ensure each collection has a unique name

**Comment by mwerla** [comment]
@jacobthill This task is only to create the field in the profile or also to fill in that field for all the collections? Since the task is closed already, can you please note what was done and if there is anything else that still has to be done to start using that field in production?

**Comment by jacobthill** [comment]
Yes, this task was to create the field and add it to the application profile which has been done. It has not yet been exposed in the application. There is an open ticket for that https://github.com/sul-dlss/dlme/issues/1326
