### ISSUE TITLE
What is the trigger for a transform?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme-transform#8]
What action starts the fargate task?

**Comment by justinlittman** [comment]
What do we gain by running as a fargate task at all vs locally/manually?

**Comment by jcoyne** [comment]
@justinlittman this was requested by the infrastructure group so that we can demonstrate ability to do this transform outside of just Jacob's local environment. We can discuss more in our meeting today.

**Comment by jcoyne** [comment]
Answered in DLME sul-dlss/dlme#386
