### ISSUE TITLE
Debug NOT FOUND error reporting #45

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#88]
I have hundreds of files, some have values for ‘type’ and ‘language’ in the raw data, some do not. 
- [ ] If there is a value, it needs to be normalized by passing it through the translation map. 
- [ ] If the value in the raw data is not in the translation map, I need an error message reporting the value in the raw data so I can add it to the translation map. 
- [ ] If there is no value in the raw data, no error should be reported. 

The way I am working is by running everything through DebugWriter and then when I see no more problems trying it on the JsonWriter to ensure that the IR validates. Its hard to debug using the JsonWriter because the output is not very readable. @jcoyne if this is not the way I should be doing this, I need you to clarify a better approach. You have mentioned a couple times that DebugWriter does not handle validation which I think I'm confused about. I get that the JsonWriter writes the IR and validates it so we can catch errors but I think I need to catch this kind of error earlier in my workflow.

**Comment by jcoyne** [comment]
It sounds like there should be a separate ticket for "The DlmeDebugWriter should do validation"

**Comment by justinlittman** [comment]
@jacobthill If you use the Traject config described [here](https://github.com/sul-dlss/dlme-transform#unmapped-languages), you should find it passes acceptance criteria. Please verify.

**Comment by jacobthill** [comment]
@justinlittman it might pass the first two criteria but I believe it fails on the last. I think what I'm seeing is a case of no value in the raw data and I'm getting an error message. I can confirm that it passes the first two criteria once I get past this error message. Here is the message:
```[ERROR] Transform produced invalid data.

The errors are: {"cho_language"=>{0=>["must not be one of: NOT FOUND"]}}

The data looked like this:
{
  "cho_title": [
    "Seyran= fragment.",
    "Le Monde Diplomatique, 1982.11.??. (sayfa: 12)."
  ],
  "cho_language": [
    "NOT FOUND"
  ],
  "cho_edm_type": [
    "text"
  ],
  "id": "http://digital.sabanciuniv.edu/abidindino/kupur/3040200003145.pdf",
  "agg_data_provider": "Sakip Sabanci Museum",
  "agg_provider": "Sakip Sabanci Museum"
}```

I think the ```"cho_language"=>{0=``` means no value in the raw data, correct?

**Comment by justinlittman** [comment]
Can you show me what your config is for `cho_language`?

**Comment by jacobthill** [comment]
I think this can be closes @jcoyne
