### ISSUE TITLE
Translation map should recognize capital and lowercase spellings

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#92]
Currently if 'Poster' is in the metadata and 'poster' is in the translation_map a NOT FOUND error is raised. Can we downcase values before they are passed to the translation_map or solve this in some other way?

**Comment by justinlittman** [comment]
Planning to implement downcase macro. I don't see a more elegant way of handling this.

**Comment by jcoyne** [comment]
@justinlittman I don't think anything is needed here. Just use `transform(&:downcase)` in the configs.
