### ISSUE TITLE
Rename BnF Macro or move name spaces

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#93]
The namespaces in the BNF macro are not unique to BnF data. I use these namespaces in sakip-sabanci-config.rb, for example. I'm not sure what the name should be.

**Comment by jcoyne** [comment]
Would `SRW` be a good choice?

**Comment by jacobthill** [comment]
I don't think so. I'm actually not clear on what the name is supposed to reflect. I can share some details that might help you decide. SRW is a standard maintained by LOC roughly equivalent to OAI-PMH (which is maintained by OAI) but both use dc: and oai_dc. So dc and oai_dc will be common to most configs. In addition most will need one or the other of srw or oai-pmh. So, I'm confused about what to call it.

**Comment by jcoyne** [comment]
Since it's using the srw:record, at the top of the xpath query, that makes the most sense to me, unless you have another alternative.

**Comment by jcoyne** [comment]
@jacobthill I suspect you are trying to do too much with one constant.  I made the SRW macro and here's an OAI macro you can use for SSM: https://github.com/sul-dlss/dlme-transform/pull/96

**Comment by jacobthill** [comment]
Ok that works
