### ISSUE TITLE
Convert harvard/stuart_cary_welch to csv

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-transform#933]
https://github.com/sul-dlss/dlme-transform/blob/main/config/metadata_mapping.json#L309 needs to be updated to `.csv`

and

https://github.com/sul-dlss/dlme-transform/blob/main/traject_configs/harvard_stuart_cary_welch.rb needs to be refactored to read from the CSV.

**Comment by jacobthill** [comment]
I think we can't harvest this collection in Airflow because it has a custom API. Our xml driver will only grab the first page of results.
