### ISSUE TITLE
parse_csv returns Nil in some cases

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#939]
In some cases the `parse_csv` macro returns `Nil` which clashes with any traject methods that follow e.g. if `gsub` is called after. This is one of the reasons Harvard IHP is failing. 

`to_field 'cho_publisher', column('originInfo_publisher'), parse_csv...` is returning `Nil` and `arabic_script_lang_or_default`. I have confirmed this by commenting out that line and running the transform against the whole collection. It passes locally once I add some missing language values to our translation maps. 

To reproduce, you'll have to harvest all of the IHP set and run the config locally.

**Comment by aaron-collier** [comment]
@jacobthill I put up a small PR for this, but at the end of havard/ihp I'm getting a different error:

```
E, [2022-10-12T15:16:41.112928 #74406] ERROR -- : Transform produced invalid data.

The errors are: [#<Dry::Validation::Message text="unknown language found (NOT FOUND)" path=[:cho_language] meta={}>]}

The data looked like this:
The record id is: 990121756820203941
```

Unrelated, so I'm not sure it should hold up the other PR..
